### ISSUE TITLE
What should the version number be *between releases*?

### ISSUE THREAD

**Issue by chrisdew** [mojombo/semver#124]
What should the version number be _between releases_?

This is NodeJS/NPM specific for me, but I'm sure it's a general issue. 

Currently I use odd patch version between releases, while released versions have even patch versions.

Is this a good idea?

**Comment by ryantheleach** [comment]
Sure, but continuous integration / test builds going out to users dictates that theres some sort of nightly / bleeding branch for the users to test with. unless we increment the version for every nightly, (in which case they are going to rise extremely rapidly) then it's going to be hard to maintain semver unless people are extremely vigilant.

An example.

We have a bleeding branch that was 6.0.0 that changed to 6.1.0-snapshot, then was promoted to 7.0.0 due to major changes.

A hotfix comes out, but our bleeding is already forward, it gets ported to stable, which had also been changed to 6.1.0-snapshot, but hadn't yet had any changes applied.

we can either go backwards to 6.0.1 on our stable, or go forward to 6.1.0 without any new features.

mean while our nightlies never saw a 6.1? that seems odd.

**Comment by jwdonahue** [comment]
@chrisdew, I believe @Haacked answered your question in the affirmative. Unless you have any further questions regarding your odd/even question, please close this issue.

**Comment by silkentrance** [comment]
@jwdonahue please close as it is counter productive.

**Comment by jwdonahue** [comment]
@chrisdew, can you please close this issue? I don't have the sauce and we're trying to reduce the number of none actionable open issues.  Thank you.

**Comment by silkentrance** [comment]
@chrisdew you can always label/tag your version, e.g. -SNAPSHOT, as in the maven world. However, if you are going to release such interim versions, you must further qualify the tag, e.g. -SNAPSHOT-1, since npm does not allow you to replace an existing version.

**Comment by silkentrance** [comment]
@Tieske well, with maven you can always deploy such interims, called snapshots, to your configured snapshot release repository. with npm this is different, since it does not support such a concept. as such, you need to qualify the interim release tag by a distinct number.

**Comment by Tieske** [comment]
from semver perspective those are implementation details. If anything they should be build-metadata in semver parlance imo.

**Comment by silkentrance** [comment]
Which is why we should close this as it is process related and already supported by the semver spec.

**Comment by jwdonahue** [comment]
@chrisdew, please close this issue at your earliest possible convenience.

**Comment by jwdonahue** [comment]
My thinking on this problem has been evolving.  We all know that spec says bump the patch or minor field and attach a prerelease tag to it.  I've recently (over the past couple of years) been coming around to the idea that there is no "in-between-release version".  Releases are synonymous with publications.  SemVer versions should not be applied to any unreleased intermediary products what-so-ever.  That implies no version strings in source code, but I digress.  

Since SemVer version strings are only applied to publications (ie, public releases), all that is left to decide is exactly what comprises a publication?  My answer to that question is; it depends on your workflows.  My personal favorite approach is just use build numbers and other build meta identifiers for everything that is "released" internally, such as from the build server to the test automation labs and that sort of thing, then only apply a SemVer version to bits that deemed worthy of releasing to the public (early flight tests, betas, RC's, etc) and what version on put on those, depends on what you've changed and whether it breaks anything.

**Comment by jwdonahue** [comment]
@alexandrtovmach, can we slap a "question answered" tag on this thread and close it please?
