### ISSUE TITLE
Your article is now available in German

### ISSUE THREAD

**Issue by MatthiasApsel** [mojombo/semver#166]
For the German-speaking audience we have put up a translation of this article in our blog at http://blog.selfhtml.org/2013/11/08/semantische-versionsnumerierung-2-0-0/.
SELFHTML e.V. is a German non-profit association dedicated to helping non-professionals to use web technologies properly for their own purposes, for instance create and maintain their own website.

**Comment by dg9ngf** [comment]
I'm going to link to semver.org on my de+en website and I'd very much like to see a German translation there. To bring things to an end, could I just create that pull request from the existing content? The content is not mine, but it's CC-licensed, so I guess it should be possible. I'm not going to claim owner- or authorship since I won't be doing much. Except for spelling updates maybe.
