### ISSUE TITLE
Is it a PATCH version to strict?

### ISSUE THREAD

**Issue by krzysiekpiasecki** [mojombo/semver#313]
The version in general reflects state of the software. __After writing additional unit tests should I release new Minor version?__ Sounds strange.

I think the problem is that patch is strictly connected only to the bug fixes that corrects invalid behavior.

IMO the better is:

MINOR - Only new software function
PATCH - bug fixes, internal code changes and improvements (faster algorithms, coding standard, tests, etc.)

We just patching existing functions and don't brake MINOR version.

**Comment by FichteFoll** [comment]
See also this discussion: https://github.com/mojombo/semver/issues/215

Though, if you only add tests but don't change anything in functionality, I wouldn't make a release at all.

**Comment by krzysiekpiasecki** [comment]
Versioning is all about state of the software and semantic is only a way to name the changes - nothing more.

Every commit has a potential to be a part of the next release and spec should be clear and allow to do it. I still think the patch version is not correct defined. Again patching is not only a bug fixing but also other changes in a state of the software that don't break MAJOR.MINOR version. So lack of documentation is also patching, etc ...

Thanks for a thread #215 @FichteFoll

**Comment by xmstspider** [comment]
What about Major.Minor.Patch.Build for unit tests? I believe this is used in .NET world...

**Comment by krzysiekpiasecki** [comment]
I believe we're distributing the source code with unit tests. The changes in tests should be reflected in a version number not in metadata component.

**Comment by arcticicestudio** [comment]
I'd recommend to merge the new tests into the next regular release version.
But if you want to release a new version only with merged tests, you should increase the MINOR since you wrote **additional** unit tests which is coverd by
> MINOR version when you **add** functionality in a backwards-compatible manner [...]

This is seen from your specific case perspective where unit tests are handled as a new functionality.

**Comment by krzysiekpiasecki** [comment]
I follow your recommendation @arcticicestudio which is closest to me.

**Comment by LinusU** [comment]
As a module consumer, I feel that it would be very weird if additional test cases where released as a minor release. Since semver is about versioning the public api, and since the tests aren't part of the public api (if the tests is bundled or not is not important, what is important is if it's considered to be a part of your public api).

**Comment by jwdonahue** [comment]
If tests are shipped, they are very much part of the API, as they add documented use cases for those API's.
