### ISSUE TITLE
Supporting multiple version & Major Version

### ISSUE THREAD

**Issue by JonathanMagnan** [mojombo/semver#395]
On one of my project, someone asked me to follow Semantic Versioning, here is the discussion: https://github.com/zzzprojects/html-agility-pack/issues/74

However, I have some concern about **MAJOR** version since it seems that doesn't fit with all kind of project.

I would like to know how you will manage when multiple version is supported at the same time.

Let say the project has two version:
- v1.x (have over 4 million downloads)
- v2.x (a complete revamp of the library from scratch)

Even if the v2.x is out, I must still support the v1.x since not everyone can move to the v2.x since there is several breaking change.

By looking at the Semantic Versioning:
- If I introduce a new breaking change in the API for the v2.x, I just increment the major version to make it v3.x, so far, everything makes sense.
- If I introduce a new breaking change in the API for the v1.x, I cannot increment the major version for some obvious reason.

So how do you propose to handle breaking change when you support two version at the same time?

**Comment by derekhofmann** [comment]
You want to introduce breaking changes so your customers won't have to deal
with breaking changes. That's an interesting paradox!

**Comment by jeme** [comment]
Everything below is just my opinion....

You find your self in this scenario due to a bad choice.
It sounds like you did a "Angular"... What I mean by that is that you did the same mistake that the Angular team did, creating a entirely new product but had a deep desire to reuse the name of the old one...

You should have selected a new name for it... It could relate to the old name, just like Microsoft released AspNet and AspNetCore, they are entirely different frameworks, but there is a high relation between the two in terms of idea, background, team... Because they each have their own name they can live on and release new versions with or without breaking changes independently of each other. (I don't think they use Semver but that doesn't matter for the argument)

That is not to say that you would never move to 2.0 for a application/framework and then not continue work on 1.x, that does certainly happen but the motivation is maintenance (Bug fixes etc.) and not to continue development on it, adding new features etc... So the motivation of keeping compatibility is also high which means you should never have to face breaking changes. (What a breaking change is can then be discussed...)

Think about it, if you begin to add new features etc. to the old 1.x maintenance branch, your product is likely to drift apart on a functional level as well meaning that it only becomes more evident that 1.x and 2.x are actually different products...

**Comment by JonathanMagnan** [comment]
Thank you @jeme for your opinion.

I understand your point.

**Project Name**
You cannot change so easily product name. There are thousands of links that point to a project URL, or NuGet Package (https://www.nuget.org/packages/HtmlAgilityPack/).

Modifying the product name cannot be done so easily as you build your reputation on the project name and all external linking is done on it.

`AspNet` and `AspNetCore` are two very different product which both are ongoing development. I don't think this example is the best fit for my scenario.

Almost every library `jQuery`, `Bootstrap`, `Angular`, `Windows`, `Apple IOs`, etc. doesn't change the project name but increment the major version.

Modyfing product name is a simple `NO`

**Breaking Changes**
As you said, what's a breaking change can be discutable.

Should it be introduced or not is also another question!

But the point is it seems that this Semantic Versioning doesn't handle this basic scenario.

**Major Version**
The Semantic Versioning work very great for a big library that is under development for years. By example, Bootstrap who is under ALPHA/BETA since 2014.

When they release a major version, their API is already well tested by millions of developers around the world. So they likely not do any `Breaking Changes` for this version or previous version.

However, for rapid development product, the API may be broke a few times since we don't have the same user base, developer team, budget, etc. 

We don't want to stay in `BETA` for years either since we need to push forward to stay motivated. If we keep incrementing the **MAJOR** version every time there is an API break, we make even users lose track of what's a **MAJOR** version since they are used to see this version incremented when there is a whole library revamp or a very big change.

So far, it seems the definition of a **MAJOR** version in this Semantic Versioning go against how 99,9% of library manage it.

Best Regards,

Jonathan

**Comment by FichteFoll** [comment]
From having worked with semver without any issues so far and considering its adoption, especially on npm, I wonder where this 99.9% figure is coming from.

If you don't agree with the premise of following the semver spec, then don't do it. This decision is entirely on you. Either you promise your users/customers that they have a numbering system they can systematically rely on by following semver, or use a custom versioning system based on "feels". However, do not do the latter and declare you're following semver.

FireFox and Chrome increase their major version regularly every X weeks, although they use a slightly different versioning system.

Imo, Angular did a huge mistake with declaring its successor as "Angular 2", just as @jeme explained. It's basically an entirely different product but uses the same name.

Windows is kind of weird, but they *do* have lots of backwards compatibility in their API because software from previous OSes is expected to continue working on the latest. Also, since Windows 10 is supposedly their final OS, it can probably be considered a product on its own with having its own version numbers. Either way, Windows isn't following semver either.

**Comment by JonathanMagnan** [comment]
Hello @FichteFoll ,

I know the decision is on my side, but I just want to understand this semantic better to make sure I take the right decision for this project or any other situation that may happen in the future.

You are right, perhaps the 99,9% is wrong and exaggerated.

Again you are right, `FireFox` and `Chrome` increase they major version regularly, but they also stop to support the previous version and keep moving forward.

I believe the whole problem on my situation is that I will support two different generation of this product using the same name. I understand better the `Angular 2` problem @jeme reported.

If I use a different name by generation, everything is fine. However, if I want to use the same name and keep supporting a previous generation, that simply doesn't work.

Thank for the help,

Best Regards,

Jonathan

**Comment by FichteFoll** [comment]
Well, the fundamental motivation for this issue seems to be this:


> - If I introduce a new breaking change in the API for the v2.x, I just increment the major version to make it v3.x, so far, everything makes sense.
> - If I introduce a new breaking change in the API for the v1.x, I cannot increment the major version for some obvious reason.

Say you want to introduce a breaking change in major 1, the first question should be: "why?", then continued with: "Can't I just leave it in there? If I do API breakages regularly, maybe I should be using pre-releases?"
After all, if you break the API of your major 1 product, people will have to investigate the changes and evaluate whether they need to update their code. In which case they might as well jump to major 2 altogether.

**Comment by jeme** [comment]
Not sure if you got my updates, my initial conclusion was that you where headed down the path that Angular did, I revised that to not being sure which scenario you would place your self in...

There are two general valid scenarios here in my opinion:
 - **A**) You wish to advance to 2.0, and you just keep 1.x in maintenance (fixing bugs etc, but never more)
 - **B**) You have changed 2.0 substantially compared to 1.x and you wish to keep growing both.

A is ok, and B should warrant a rename.

> You cannot change so easily product name. There are thousands of links that point to a project URL, or NuGet Package (https://www.nuget.org/packages/HtmlAgilityPack/).
> Modifying the product name cannot be done so easily as you build your reputation on the project name and all external linking is done on it.

These are interesting and IMO bad motivations, and I think it has been tried and failed more frequently than it has succeeded (If it has ever)... And I would guess that this was the exact same motivation behind Angular 2 and AspNetCore... So lets evaluate.

## The Angular Case (My Favorite)

**Case:** a Scenario **B** that tried to keep to **A** and failed badly.

So the Angular team build an entire new product and branded and released it under Angular 2, this caused quite a commotion as the expectation from the user-base was that it was the next iteration on Angular, which you would upgrade to, yes it did require some effort (After all, 1.x -> 2.0 means breaking changes, and they didn't even use SemVer at the time so no one knew)...

> Modifying the product name cannot be done so easily as you build your reputation on the project name and all external linking is done on it.

Because Angular 2 had almost nothing to do with Angular 1.x, following the same belief with building on the same name, this backfired greatly and there was a massive uproar in the community, causing more damage than good.

The situation today is that we have two entirely different products, AngularJS (the 1.x branch, https://angularjs.org/) and Angular (2.x and onwards... https://angular.io/)... **They literally changed naming in the end...** I am not sure they fully realized that them self yet though >.<... And as a consequence, I don't think they will turn in a AngularJS 2.0 any time soon, even though they are now free to do so (being under a different name, different urls etc)... But I still think they hold on to the idea that people should instead adopt Angular (no JS)... But just because they pass 2.0 on AngularJS, there is no reason they can't still provide a "Migration" path, it's just a different migration path, similar to how Aurelia outlined a Migration path from Angular to Aurelia... And how Microsoft Outlines one from AspNet to AspNetCore (although it just being blog posts etc.).

Angular has recovered, but I don't believe for one moment that that was because they did what they did, on the contrary, I think it would have grown faster if they had just gone with the rename. I Think they recovered because Angular has good parts...

Angular recently adopted SemVer, AngularJS are still just arbitrary versions I beleive

## AspNetCore vs AspNet

**Case:** a Scenario **B**.

> AspNet and AspNetCore are two very different product which both are ongoing development. I don't think this example is the best fit for my scenario.

So just like Angular vs AngularJS? >.<...

Maybe it doesn't fit your scenario, I was making the comparison to Angular... Where Google made a mess, and perhaps Microsoft learned from it or perhaps something else happened, because AspNetCore
was actually first advertised as AspNet 5 (The next iteration for AspNet) - They since then thankfully ended up changing the name.

But when you consider the Owin startup class of AspNet and compare that to AspNetCore then they are in my opinion far more similar than the Angular case ever were... Yet they ended up with renaming before release and Angular didn't...

Neither uses Semver to my knowledge though.

## jQuery, Bootstrap

**Case:** a Scenario **A**.

Notice a little sentence on jQuerys page: "The 1.x and 2.x branches no longer receive patches"... 
I do believe that it goes for both of these projects that once they move Major version, they either completely deprecate support for older versions OR they only ever deliver bug fixes...

You can't always be so harsh as jQuery unless migration to next major version is both easy and free. If neither is the case then your in the scenario where you need to keep delivering patches to a previous version... Aka. your 1.x branch...

But this is the scenario where your motivation is only ever to release patches (bugfixes) and not even new features, while you could deliver new features as well without breaking anything for your users, I would discourage that because those new features should be your argument for getting your customers to upgrade.

If you keep pleasing them with the same new features on 1.x, then why should they ever adopt 2.0... and in such a scenario you have to do double the work and when you eventually release 3.0, 4.0 etc... you end up having to still maintain 1.x because you have so many customers on that branch, basically your digging your own grave.

## Windows

Well, windows versioning has never been rational, it's just marketing version. So it's the worst example of using a realiable and understandable versioning scheme ever >.<... 

## Linux

Linux is another more interesting case here, could you imagine a world where you just had:
 - Linux: 10.0.0 (what we know as Ubuntu)
 - Linux: 11.0.0 (what we know as Suse)
 - Linux: 12.0.0 (what we know as Centos)
 - Linux: 13.0.0 (what we know as Redhat)
 - Linux: 14.0.0 (what we know as Fedora)

Not really right?... because there is no linearity between them, they have developed in different directions which is why we have different names for different branched version of the same core (Linux)

They have gained different levels of popularity, but they can all refer back to the same name, Linux.

The reason why I bring this up as an example here is because that this is what happens if you continue evolving your 1.x branch, it's what happened to Angular vs AngularJS, it's what happened to AspNet vs AspNetCore etc...

If you keep actively evolving a previous version of your software, eventually it becomes a different thing than the new version, and that is why I think it then warrants a new name.

-----------------------------------------------------

SO!.... Conclusion... Which Scenario do you wan't to be in?....
This would be my advice and also the approach I would end up following:

Scenario **A**?
 - Advance to 2.0.
 - Put 1.x into maintenace
 - Don't deliver new features to 1.x (You wan't to move your customers to 2.0, so don't give them more reasons to stay)
 - Don't deliver breaking changes to 1.x 
 - Do deliver patches (bug fixes) to 1.x (1.x.1, 1.x.2, 1.x.3 etc)
 - Help your customers to adopt 2.0. (Migration paths, guides etc.)

Scenario **B**?
 - Change the name for 2.0 and start from 1.0 again.
 - Make the name relate able to the old project, if that makes sense.
 - Refer to the new great thing from the former one.
 - Help your customers move to the new product (Migration paths, guides etc.)
 - Eventually let go of the old one and put it in the hands of the community (it's not where your heart is any more)

An alternate option, abandon your use of SemVer and tell your customers.

**Comment by JonathanMagnan** [comment]
Thank you @FichteFoll , @jeme 

Just to let you know that I have read your both answer and appreciate really the time you took.

I will take a few days to think about it as there is `pro` and `con` like any versioning.

One question though:
- Why the semantic versioning is still in `2.0.0` if a lot of spelling mistake and text addition has been done since the `Semantic Versioning 2.0.0` has been released?

Best Regards,

Jonathan

**Comment by majormoses** [comment]
First off these are all excellent points and I echo them. Rather than giving another similar answer I will focus on the question about the semver spec following semver and what I believe the root need of what your user is asking for.

> Why the semantic versioning is still in 2.0.0 if a lot of spelling mistake and text addition has been done since the Semantic Versioning 2.0.0 has been released?

Well when projects choose to release is almost always at the discretion of the maintainers and what their community/customers wants. I am a maintainer for several different open + closed source projects across several different orgs. They all have different needs and resources which means that they often have different release schedules and cycles. For some of them we take the stance that a release should be cut on each **functional** change within 24 hours. Others we wait for a few new features before cutting a release. For things like spelling, typos, documentation, etc we wait until there is a functional change. Taking a quick peak at: https://github.com/mojombo/semver/compare/v2.0.0...HEAD I do not really see any new "features" and I am guessing that the value of versioning the spec with a bunch of patches that are not actually fix anything that a user would need to pull in is not enough to outweigh the cost of cutting a release.

I will avoid arguing for semver as others have already made great cases for it. I could totally be wrong but I think that your users are asking for something that is partially facilitated by semver; IMHO you could accomplish their needs with another versioning scheme that is more palpable to you. The more important thing is not which version scheme, it is more important that they understand the upgrade path. A responsible developer/operator will do some kind of risk assessment with varying levels before upgrading. Ideally it should not be required to have them read the entire source diffs and be a guru in your project to do so at the very basic level. The easiest solution is to provide this is via a understandable versioning scheme and a good changelog.

**Comment by JonathanMagnan** [comment]
Hello @majormoses , 

Thank your for this additional information.

There is some stuff in which I could argue but at one point, it's more some personal opinion and doesn't add any value to the `Semantic Versioning`.

I will close this issue since there is nothing more I can add and I understand very well point everyone provided in this thread.

Thank a lot for your help,

Best Regards,

Jonathan
