### ISSUE TITLE
Why is it so strict about resetting minor version to zero?

### ISSUE THREAD

**Issue by vi** [mojombo/semver#9]
```
... the minor version and patch version MUST be reset to zero.
```

What will break if the minor version is not reset to zero while incrementing the major version number? Not resetting it will allow to preserve more or less linear flow of versions on minor (but API breaking) change.

For example, in `1.5 -> 1.6 -> 1.7 -> 2.8 -> 2.9` we can talk about short "version 6" or "version 9" instead of saying the two numbers every time and psychologically rebasing the development to the beginning of major cycle ("2.0" it will seem like "completely new version with new API" rather than "next version + some API change").

May be better be `SHOULD be reset to zero` or `MUST be reset to zero or incremented by one`?

**Comment by dylanopen** [comment]
> What about prereleases? I'm not sure why it's useful to know how many releases there have been, but it's usually pretty easy to count - `npm show $package versions | wc -l`, for example.

Yes, it's obviously quite easy to count (especially with online package registries like crates.io just listing the number of versions for you). It's just personal preference: I really like my version number to represent all of the minor versions we've ever released.

> A breaking change might be small, but also might be a complete rewrite, in which case .0.0 is the only correct choice.

Yes, when I changed my Realms backend from a pixel frame-buffer based library to an opengl-based library, I reset to version 1.0.0 as almost everything about the API had changed. So the minor versions would no longer have meaning, as they didn't refer to the current version. Maybe a better way of wording it is that, as long as the minor and patch versions relate to the current state of the library (i.e. the features and patches are still in the API) it doesn't make sense for me to reset the version, as all those patches still exist. Basically, as all the minor versions still have effect in the codebase, why make it seem as though we're throwing it all away?

I really like that idea, actually. Resetting the minor and patch when the major version changes loads of features and the API can't easily be directly translated to the newer version, but I would then keep the minor and patch version if the major version didn't break half the features.

> The proper thing maintainers should learn from that problem, is to find ways to _not do breaking changes at all_, as opposed to piling up breaking changes into a big release. For example, ship the breaking behavior behind an option in a minor - then, even if you want to flip the default, the "break" is very easy to work around.

I do agree that breaking changes should always be avoided if possible. However, as you say, breaking changes are often necessary. My main point with my reasoning was that as a library maintainer, I quite often push breaking changes which just, say, change a function to accept a reference instead of a moved value. I personally much prefer pushing one, small, breaking change as a major release, rather than changing 50 things in a single release (making migration really difficult).

In my mind, I would be more wary of pushing smaller major versions if the minor and patch reset. But this way, whenever I make a small breaking change, I release a new version, and it's really easy for my users to update.

> > If I instead reset the minor and patch, I'd be much more weary of making major releases
> You're _supposed_ to be :-) Breaking changes are painful and costly. They are often necessary but never ideal.

What I meant by the issue of being wary of major versions is **not** that we should be pushing out as many breaking changes as we possibly can, but rather that my opinion is that it's better to release 10 small major breaking changes than one large change which causes half your codebase to be invalid. That last one is a migrating nightmare.

*To be honest I really didn't expect a reply to a 13 year old post, but thanks for taking the time to respond* 😆
